#!/bin/bash

# TX Ultimate HA Failover - Quick Installation Script
# This script helps you set up your TX Ultimate configuration

set -e

echo "=================================="
echo "TX Ultimate HA Failover Installer"
echo "=================================="
echo ""

# Check if secrets.yaml exists
if [ -f "secrets.yaml" ]; then
    echo "⚠️  secrets.yaml already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Using existing secrets.yaml"
        SKIP_SECRETS=true
    fi
fi

# Create secrets.yaml if needed
if [ "$SKIP_SECRETS" != "true" ]; then
    echo ""
    echo "📝 Creating secrets.yaml..."
    echo ""

    read -p "Enter your WiFi SSID: " WIFI_SSID
    read -sp "Enter your WiFi Password: " WIFI_PASS
    echo ""
    read -sp "Enter fallback AP password: " AP_PASS
    echo ""

    # Generate API key
    echo "🔑 Generating API encryption key..."
    API_KEY=$(openssl rand -base64 32 | head -c 32)

    cat > secrets.yaml << EOF
# secrets.yaml - Generated by install.sh
# NEVER commit this file to git!

wifi_ssid: "$WIFI_SSID"
wifi_password: "$WIFI_PASS"

# Fallback access point password (when WiFi fails)
ap_pass: "$AP_PASS"

# API encryption key (generated)
api_key: "$API_KEY"
EOF

    echo "✅ secrets.yaml created successfully!"
fi

# Configure device settings
echo ""
echo "📡 Device Configuration"
echo ""

read -p "Enter device name (e.g., 'living_tx'): " DEVICE_NAME
read -p "Enter friendly name (e.g., 'Living-TX'): " FRIENDLY_NAME
read -p "Enter device IP address (e.g., '192.168.1.101'): " DEVICE_IP
read -p "Enter Home Assistant IP (e.g., '192.168.1.100'): " HA_IP
read -p "Number of relays (1-3) [2]: " RELAY_COUNT
RELAY_COUNT=${RELAY_COUNT:-2}

echo ""
echo "🌍 Location Configuration (for nightlight)"
echo "   You can find your coordinates at: https://www.latlong.net/"
read -p "Enter latitude (e.g., '53.3498°'): " LATITUDE
read -p "Enter longitude (e.g., '-6.2603°'): " LONGITUDE

# Create custom configuration
echo ""
echo "✏️  Creating your custom configuration..."

cat > tx_ultimate_failover.yaml << EOF
# TX Ultimate HA Failover Configuration
# Generated by install.sh

substitutions:
  # Device identification
  name: '$DEVICE_NAME'
  friendly_name: "$FRIENDLY_NAME"

  # Network configuration
  ha_ip: "$HA_IP"
  ha_port: "8123"
  device_ip: "$DEVICE_IP"
  ap_ssid: "$FRIENDLY_NAME-Fallback"

  # Monitoring intervals
  wifi_check_interval: "600s"
  ha_check_interval: "300s"
  nightlight_check_interval: "5"

  # Hardware configuration
  relay_count: "$RELAY_COUNT"
  vibra_time: 400ms
  button_on_time: 500ms

  # LED Colors - RGB format (0-100)
  button_brightness: "0"
  button_color: "{0,0,90}"

  nightlight: "on"
  nightlight_brightness: "0.2"
  nightlight_color: "{80,70,0}"

  touch_brightness: "1"
  touch_color: "{0,100,100}"
  touch_effect: "Scan"

  long_press_brightness: "1"
  long_press_color: "{100,0,0}"
  long_press_effect: ""

  multi_touch_brightness: "1"
  multi_touch_color: "{0,0,0}"
  multi_touch_effect: "Rainbow"

  swipe_left_brightness: "1"
  swipe_left_color: "{0,100,0}"
  swipe_left_effect: ""

  swipe_right_brightness: "1"
  swipe_right_color: "{100,0,70}"
  swipe_right_effect: ""

  # Status indicator colors
  no_wifi_color_r: "1.0"
  no_wifi_color_g: "1.0"
  no_wifi_color_b: "0.0"

  ha_down_color_r: "1.0"
  ha_down_color_g: "0.0"
  ha_down_color_b: "0.0"

  ha_online_color_r: "0.0"
  ha_online_color_g: "0.75"
  ha_online_color_b: "1.0"

  # Location for sunrise/sunset
  latitude: "$LATITUDE"
  longitude: "$LONGITUDE"

  # Pin assignments (TX Ultimate standard)
  relay_1_pin: GPIO18
  relay_2_pin: GPIO17
  relay_3_pin: GPIO27
  relay_4_pin: GPIO23

  vibra_motor_pin: GPIO21
  pa_power_pin: GPIO26

  led_pin: GPIO13
  status_led_pin: GPIO33

  uart_tx_pin: GPIO19
  uart_rx_pin: GPIO22

  audio_lrclk_pin: GPIO4
  audio_bclk_pin: GPIO2
  audio_sdata_pin: GPIO15

  touchpanel_power_pin: GPIO5

# Import the base configuration
<<: !include tx_ultimate_base.yaml
EOF

# Check if base file exists
if [ ! -f "tx_ultimate_base.yaml" ]; then
    echo "⚠️  tx_ultimate_base.yaml not found!"
    echo "   Using tx_ultimate_failover.yaml as standalone configuration"

    # If the original file exists, use it as base
    if [ -f "esphome_tx_sonoff.yaml" ]; then
        cp esphome_tx_sonoff.yaml tx_ultimate_base.yaml
        echo "   Created tx_ultimate_base.yaml from esphome_tx_sonoff.yaml"
    fi
fi

echo ""
echo "✅ Configuration complete!"
echo ""
echo "📋 Summary:"
echo "   Device name: $DEVICE_NAME"
echo "   Friendly name: $FRIENDLY_NAME"
echo "   Device IP: $DEVICE_IP"
echo "   Home Assistant IP: $HA_IP"
echo "   Relays: $RELAY_COUNT"
echo "   Location: $LATITUDE, $LONGITUDE"
echo ""
echo "Next steps:"
echo "1. Review and edit tx_ultimate_failover.yaml if needed"
echo "2. Flash to device: esphome run tx_ultimate_failover.yaml"
echo ""
echo "📖 See CONFIGURATION_EXAMPLES.md for customization options"
echo ""
