# TX Ultimate HA Failover - User Configuration Example
#
# This is an example configuration file showing all available options.
# Copy this file and customize it for your specific device.
#
# Quick Start:
# 1. Copy this file to your ESPHome folder
# 2. Rename it (e.g., living_room_tx.yaml)
# 3. Update the substitutions below
# 4. Create/update your secrets.yaml
# 5. Flash: esphome run living_room_tx.yaml

substitutions:
  ###### CHANGE ME START ######

  # ================================
  # DEVICE CONFIGURATION
  # ================================
  name: 'living_tx'
  friendly_name: "Living-TX"

  # ================================
  # HOME ASSISTANT SETTINGS
  # ================================
  ha_url: "https://192.168.50.168:8123"   # Your Home Assistant URL
  ha_api_token: "Bearer YOUR_LONG_LIVED_TOKEN_HERE"  # See instructions below

  # ================================
  # HARDWARE CONFIGURATION
  # ================================
  relay_count: "2"                   # Number of relays (1-3)
  vibra_time: 400ms                  # Vibration duration
  button_on_time: 500ms              # Button press duration

  # ================================
  # LED COLORS - RGB format (0-100)
  # ================================
  button_brightness: "0"
  button_color: "{0,0,90}"           # Button active color (blue)

  nightlight: "on"                   # "on" or "off"
  nightlight_brightness: "0.2"
  nightlight_color: "{80,70,0}"      # Nightlight color (warm white)

  touch_brightness: "1"
  touch_color: "{0,100,100}"         # Touch feedback (cyan)
  touch_effect: "Scan"

  long_press_brightness: "1"
  long_press_color: "{100,0,0}"      # Long press color (red)
  long_press_effect: ""

  multi_touch_brightness: "1"
  multi_touch_color: "{0,0,0}"       # Multi-touch color (off)
  multi_touch_effect: "Rainbow"

  swipe_left_brightness: "1"
  swipe_left_color: "{0,100,0}"      # Swipe left color (green)
  swipe_left_effect: ""

  swipe_right_brightness: "1"
  swipe_right_color: "{100,0,70}"    # Swipe right color (purple)
  swipe_right_effect: ""

  # ================================
  # FAILOVER CONFIGURATION
  # ================================
  ha_failover_turn_on_lights: "true"  # true for living/dining, false for bedrooms
  ha_failover_nightlight_color: "{100,0,0}"  # Red alert color when HA offline

  # ================================
  # LOCATION FOR NIGHTLIGHT
  # ================================
  latitude: !secret latitude
  longitude: !secret longitude

  # ================================
  # PIN ASSIGNMENTS (TX Ultimate standard - don't change unless needed)
  # ================================
  relay_1_pin: GPIO18
  relay_2_pin: GPIO17
  relay_3_pin: GPIO27
  relay_4_pin: GPIO23

  vibra_motor_pin: GPIO21
  pa_power_pin: GPIO26

  led_pin: GPIO13
  status_led_pin: GPIO33

  uart_tx_pin: GPIO19
  uart_rx_pin: GPIO22

  audio_lrclk_pin: GPIO4
  audio_bclk_pin: GPIO2
  audio_sdata_pin: GPIO15

  touchpanel_power_pin: GPIO5

  ###### CHANGE ME END ######

##### DO NOT CHANGE ANYTHING BELOW! #####

# ================================
# LOAD BASE CONFIGURATION FROM GITHUB
# ================================
packages:
  remote_package:
    url: https://github.com/cfpandrade/tx-ultimate-ha-failover
    ref: main  # Use 'main' for latest, or specific tag like 'v1.3.1'
    files: [tx_ultimate_base.yaml]
    refresh: 300s  # Check for updates every 5 minutes

##### My customization - Start #####

# API with encryption
api:
  encryption:
    key: !secret api_key

# OTA updates
ota:
  - platform: esphome
    password: !secret ota_pass

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.35.56  # Optional: Set your fixed IP here

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tx-Living"
    password: !secret ap_pass

##### My customization - End #####

# ================================
# HOW TO GET YOUR HOME ASSISTANT TOKEN
# ================================
# 1. Go to your Home Assistant profile (click your username in bottom left)
# 2. Scroll down to "Long-Lived Access Tokens"
# 3. Click "CREATE TOKEN"
# 4. Give it a name like "TX Living Room"
# 5. Copy the token (it's VERY long, starts with "eyJ...")
# 6. Format: "Bearer eyJ..." and add to secrets.yaml:
#    tx_status_api_token: "Bearer eyJ..."
#
# Then in this file, use:
#    ha_api_token: !secret tx_status_api_token

# ================================
# SECRETS.YAML EXAMPLE
# ================================
# Create a file called 'secrets.yaml' in the same folder with:
#
# wifi_ssid: "YourWiFiSSID"
# wifi_password: "YourWiFiPassword"
# ap_pass: "FallbackPassword123"
# api_key: "your-32-character-api-key-here"  # Generate in ESPHome dashboard
# ota_pass: "your-ota-password"
# latitude: "40.7128°"
# longitude: "-74.0060°"
# tx_status_api_token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
