# TX Ultimate HA Failover - User Configuration Example
#
# This is the ONLY file you need to customize!
# The base configuration is loaded automatically from GitHub.
#
# Quick Start:
# 1. Copy this file to your ESPHome folder
# 2. Rename it (e.g., living_room_tx.yaml)
# 3. Update the substitutions below
# 4. Create/update your secrets.yaml
# 5. Flash: esphome run living_room_tx.yaml

substitutions:
  # ================================
  # DEVICE CONFIGURATION
  # ================================
  name: 'living_tx'
  friendly_name: "Living-TX"

  # ================================
  # NETWORK SETTINGS
  # ================================
  ha_ip: "192.168.50.168"           # Your Home Assistant IP
  ha_port: "8123"                    # Home Assistant port
  device_ip: "192.168.35.56"         # Fixed IP for this device
  ap_ssid: "Tx-Living"               # Fallback AP name

  # ================================
  # MONITORING INTERVALS
  # ================================
  wifi_check_interval: "600s"        # WiFi watchdog check (10 min)
  ha_check_interval: "300s"          # HA availability check (5 min)
  nightlight_check_interval: "5"     # Minutes to check nightlight

  # ================================
  # HARDWARE CONFIGURATION
  # ================================
  relay_count: "2"                   # Number of relays (1-3)
  vibra_time: 400ms                  # Vibration duration
  button_on_time: 500ms              # Button press duration

  # ================================
  # LED COLORS - RGB format (0-100)
  # ================================
  button_brightness: "0"
  button_color: "{0,0,90}"           # Button active color (blue)

  nightlight: "on"
  nightlight_brightness: "0.2"
  nightlight_color: "{80,70,0}"      # Nightlight color (warm)

  touch_brightness: "1"
  touch_color: "{0,100,100}"         # Touch feedback (cyan)
  touch_effect: "Scan"

  long_press_brightness: "1"
  long_press_color: "{100,0,0}"      # Long press color (red)
  long_press_effect: ""

  multi_touch_brightness: "1"
  multi_touch_color: "{0,0,0}"       # Multi-touch color (off)
  multi_touch_effect: "Rainbow"

  swipe_left_brightness: "1"
  swipe_left_color: "{0,100,0}"      # Swipe left color (green)
  swipe_left_effect: ""

  swipe_right_brightness: "1"
  swipe_right_color: "{100,0,70}"    # Swipe right color (purple)
  swipe_right_effect: ""

  # Status indicator colors (0.0-1.0)
  no_wifi_color_r: "1.0"             # Yellow when no WiFi
  no_wifi_color_g: "1.0"
  no_wifi_color_b: "0.0"

  ha_down_color_r: "1.0"             # Red when HA down
  ha_down_color_g: "0.0"
  ha_down_color_b: "0.0"

  ha_online_color_r: "0.0"           # Cyan when HA back online
  ha_online_color_g: "0.75"
  ha_online_color_b: "1.0"

  # ================================
  # LOCATION FOR NIGHTLIGHT
  # ================================
  latitude: "40.7128°"
  longitude: "-74.0060°"

  # ================================
  # PIN ASSIGNMENTS (TX Ultimate standard - don't change unless needed)
  # ================================
  relay_1_pin: GPIO18
  relay_2_pin: GPIO17
  relay_3_pin: GPIO27
  relay_4_pin: GPIO23

  vibra_motor_pin: GPIO21
  pa_power_pin: GPIO26

  led_pin: GPIO13
  status_led_pin: GPIO33

  uart_tx_pin: GPIO19
  uart_rx_pin: GPIO22

  audio_lrclk_pin: GPIO4
  audio_bclk_pin: GPIO2
  audio_sdata_pin: GPIO15

  touchpanel_power_pin: GPIO5

# ================================
# LOAD BASE CONFIGURATION FROM GITHUB
# ================================
packages:
  remote_package:
    url: https://github.com/cfpandrade/tx-ultimate-ha-failover
    ref: main  # Use 'main' for latest, or specific tag like 'v1.1.0'
    files: [tx_ultimate_base.yaml]
    refresh: 300s  # Check for updates every 5 minutes

# ================================
# SECRETS (create secrets.yaml in same folder)
# ================================
# Example secrets.yaml:
#
# wifi_ssid: "YourWiFiSSID"
# wifi_password: "YourWiFiPassword"
# ap_pass: "FallbackPassword123"
# api_key: "your-32-character-api-key-here"
# ota_pass: "your-ota-password"
